### ISSUE TITLE
Missing sentence ID(s) in RP

### ISSUE THREAD

**Issue by ibleaman** [beatrice57/penn-parsed-corpus-of-historical-yiddish#1]
@beatrice57

I'm writing about two small formatting issues in the _Röyte Pomerantsen_ subcorpus, affecting three "sentences":

1. The sentence fragment that appears between `1947E-ROYTE-POMERANTSEN,211.5310` and `1947E-ROYTE-POMERANTSEN,211.5312` is missing its sentence ID. I believe this may just be an oversight, because there is an analogous fragment a few lines later that does receive a sentence ID (`211.5314`).

2. In almost all cases, the title of a joke (the first "sentence" after each `<P_integer>` code) is given a sentence ID. There are two exceptions. I'm wondering whether these should also have sentence IDs? They are:

```
( (CODE <P_35>))

( (INTJ nebekh))
```

and

```
( (CODE <P_90>))

( (INTJ hura))
 ```

I thought this might also be an oversight because all other non-sentence joke titles receive a sentence ID, e.g.:
```
( (CODE <P_34>))

( (NP (NPR roznblat))
  (ID 1947E-ROYTE-POMERANTSEN,34.836))
```

I'm happy to submit a PR if you'd prefer that. Thanks!

**Comment by ibleaman** [comment]
These 3 sentences are the only ones in the RP subcorpus that don't have an ID/CODE of `1947E-ROYTE-POMERANTSEN,integer.integer` or `<P_integer>`, except for the first line: `<BEGIN_1947e-royte-pomerantsen>`

**Comment by beatrice57** [comment]
dear isaac,

thanks for the notification.

i've made the corrections and posted them on github.
in the course of doing so, i found some other minor issues in 1946e-mark
and fixed those as well.

thanks again - it's user notifications like yours that make
it possible to improve the corpora.

i'm cc'ing seth in case the update is of interest to him...


========================================================

Please note that my Penn email addresses will expire on June 30, 2024.

After that date, you can reach me at

***@***.***

========================================================

**Comment by ibleaman** [comment]
Great!
